### ISSUE TITLE
Relative paths in problem matcher not working in 1.1

### ISSUE THREAD

**Issue by Nallebeorn** [tlgkccampbell/code-ca65#3]
After the 1.1.0/1.1.1 updates, I can no longer click on errors in the problem matcher to open files, because relative paths are treated like absolute ones (so I just get a "File not found" error). At least for me, cl65.exe outputs relative paths by default. This wasn't an issue in 1.0.4, to be clear.

**Comment by tlgkccampbell** [comment]
The behavior of the problem matchers was changed in 1.1.0 to improve consistency; as you've found out, they all assume that you're using absolute, rather than relative paths. (The upside of this is that it now correctly handles errors and warnings arising from one of cl65's built-in configurations, which always return as absolute paths).

When you invoke `cl65.exe` it will output absolute paths if you pass the input file as an absolute path. Changing your build task to pass `${file}` instead of `${relativeFile}` should do the trick. The new built-in tasks which are provided as of 1.1.0 always pass absolute paths to `cl65.exe` and should work out of the box.

Please let me know if this doesn't resolve your issue.

**Comment by Nallebeorn** [comment]
Thank you for your help! Using an absolute path as argument to cl65 did solve my problem. Good to hear this was an intentional change and not a bug.
